### ISSUE TITLE
"By Email" Dynamic Dropdown Input Issue

### ISSUE THREAD

**Issue by InspectorGadg3t** [Bre77/hibp#2]
Hello,

Great app!

The “By Email” dashboard is currently unusable for us due to the volume of email addresses that are dynamically populated in the “Email” drop-down (60,000+). Attempting to expand the “Email” dropdown on this dashboard locks up the page, requiring a refresh of the page to make the browser tab usable again. Most of the email addresses are from a spam list.

Is there something that can be done to mitigate this? A couple of options that come to mind are changing the input to a text field instead or being able to filter out email addresses from Spam Lists (IsSpamList)?

Cheers!

**Comment by Bre77** [comment]
That's a good idea, adding a text box and ignoring the dropdown should work just fine. I'll do that in the next release.

**Comment by Bre77** [comment]
This has been addressed in 1.0.6 by adding a text box to the dashboard. I may look at also adding a spamlist checkbox in the next release.

**Comment by Bre77** [comment]
Version 1.0.6 should be Cloud compatible now. Please continue to let me know if you have any feedback.
