### ISSUE TITLE
Retro active

### ISSUE THREAD

**Issue by lduriez** [Bre77/hibp#3]
Hello,

We just find out about your work, and it seems to do what we want, good job on that.

Then it's more a question than an issue, but we install a splunk "free" and we had no problem at all to install the application and configure the application. But the summary dashboard for example seems to be blank, except for the "Domains monitored".
![image](https://github.com/Bre77/hibp/assets/36005270/90a62bd1-27ae-4ede-b3c6-e89dcbeab3cb)
![image](https://github.com/Bre77/hibp/assets/36005270/2a60d4d2-50c5-4d20-beec-b37c203b948c)

I'm thinking that it's normal because it's not retro-active on previous breached we could have and we have to wait for new HIBP events, could you confirm that ?
If true, does it exist the possibility to replay previous events ?

Regards.

**Comment by Bre77** [comment]
It will pull historical data, however if you set the index before adding your API key you will need to wait an hour.

If you have waited an hour and still have no data, then use the support dropdown and look at the internal logs to see if there are errors.

I have not tested the app on the free license, but can't see why it wouldn't work.

**Comment by lduriez** [comment]
Thanks for your answer.

Indeed coming back at office this morning all the dashboards are now working 😉

So I confirm it works with free license then.

**Comment by lduriez** [comment]
Thanks for your answer.

Indeed coming back at office this morning all the dashboards are now working 😉

So I confirm it works with free license then.
