### ISSUE TITLE
Missing permission for other user besides admin

### ISSUE THREAD

**Issue by jdestinlab** [Bre77/hibp#6]
This gives all user read permission. As nobody besides admin could use the automatic lookup due to this below:
[collections/hibp-breaches]
access = read : [  ], write : [ ] 

cat /opt/splunk/etc/apps/hibp/metadata/default.meta
[]
access = read : [ * ], write : [ admin, sc_admin ]

[collections/hibp-pwned]
access = read : [ * ], write : [ ]
export = system
owner = nobody

[collections/hibp-breaches]
access = read : [ * ], write : [ ]

[transforms]
export = system

[props]
export = system

[macros]
export = system

Could you please update the app?

**Comment by Bre77** [comment]
Yes it would appear I got breaches and pwned backwards. Breaches should be read * and pwned should have no permissions since its used as a checkpoint only.

**Comment by Bre77** [comment]
I have submitted a new version to address this.

**Comment by jdestinlab** [comment]
Thanks

**Comment by jdestinlab** [comment]
Hi,

I waited two days but the new version is still not showing up in
Splunkcloud? Was it published on both?

Thanks
*Joanan Junel Destin*

**Comment by jdestinlab** [comment]
Ok, thanks for the clarification.

**Comment by Bre77** [comment]
The approval just came through, it should be available in cloud now.

**Comment by jdestinlab** [comment]
Awesome, thanks for the update!
